# Generated by Django 5.2.6 on 2025-10-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, help_text='Необязательно. Введите ваш адрес.', null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Необязательно. Широта вашего местоположения.', max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Необязательно. Долгота вашего местоположения.', max_digits=10, null=True, verbose_name='Долгота'),
        ),
    ]
