# Generated by Django 5.2.6 on 2025-10-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Текущий баланс пользователя в рублях', max_digits=10, verbose_name='Сумма баланса'),
        ),
    ]
