# Generated by Django 5.2.6 on 2025-10-27 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userbalance_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSMSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Код подтверждения', max_length=10, verbose_name='SMS код')),
                ('identifier', models.CharField(help_text='Номер телефона или email', max_length=255, verbose_name='Идентификатор')),
                ('identifier_type', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email')], help_text='Тип идентификатора: телефон или email', max_length=10, verbose_name='Тип идентификатора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(verbose_name='Срок действия')),
                ('is_used', models.BooleanField(default=False, help_text='Указывает, был ли код использован', verbose_name='Использован')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата использования')),
                ('created_by', models.ForeignKey(blank=True, help_text='Пользователь, который запросил код (если зарегистрирован)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_codes', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'SMS код',
                'verbose_name_plural': 'SMS коды',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['identifier', 'identifier_type'], name='accounts_us_identif_562816_idx'), models.Index(fields=['code', 'identifier'], name='accounts_us_code_8629d2_idx'), models.Index(fields=['is_used', 'expires_at'], name='accounts_us_is_used_1b38de_idx')],
            },
        ),
    ]
