# Generated by Django 5.2.6 on 2025-11-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usersmscode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Часто задаваемый вопрос', verbose_name='Вопрос')),
                ('answer', models.TextField(help_text='Ответ на вопрос', verbose_name='Ответ')),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения (меньшее число - выше)', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать ли вопрос в списке', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
