# Generated by Django 5.2.6 on 2025-12-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, help_text='Необязательно. Введите ваше описание.', null=True, verbose_name='Описание'),
        ),
    ]
