# Generated by Django 5.2.6 on 2026-01-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Необязательно. Введите ваш Telegram Chat ID для получения SMS.', max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
