# Generated by Django 5.2.6 on 2026-01-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_carowner_mastercustomuser_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carowner',
            options={'verbose_name': 'Автовладелец', 'verbose_name_plural': '01. Автовладельцы'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'FAQ', 'verbose_name_plural': '05. FAQ'},
        ),
        migrations.AlterModelOptions(
            name='mastercustomuser',
            options={'verbose_name': 'Мастер', 'verbose_name_plural': '03. Мастера'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Владелец', 'verbose_name_plural': '02. Владельцы'},
        ),
        migrations.AlterModelOptions(
            name='userbalance',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Баланс пользователя', 'verbose_name_plural': '04. Балансы пользователей'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='private_id',
            field=models.CharField(blank=True, help_text='Уникальный 6-значный идентификатор пользователя. Генерируется автоматически.', max_length=6, null=True, unique=True, verbose_name='Private ID'),
        ),
    ]
