# Generated by Django 5.2.6 on 2026-05-04 05:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_paymenttransaction'),
        ('order', '0015_order_workflow_penalties'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterAvailableBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Доступно, ₽')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Доступный баланс мастера',
                'verbose_name_plural': 'Доступные балансы мастеров',
            },
        ),
        migrations.CreateModel(
            name='MasterOrderEarningCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма, ₽')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Зачисление с заказа (мастер)',
                'verbose_name_plural': 'Зачисления с заказов',
            },
        ),
        migrations.CreateModel(
            name='MasterWithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма, ₽')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('reviewing', 'На рассмотрении'), ('processing', 'В обработке'), ('completed', 'Выплачено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='Заметка админа')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Возврат на баланс')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выплата подтверждена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заявка на вывод (мастер)',
                'verbose_name_plural': 'Заявки на вывод',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='masteravailablebalance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_available_balance', to=settings.AUTH_USER_MODEL, verbose_name='Мастер (пользователь)'),
        ),
        migrations.AddField(
            model_name='masterorderearningcredit',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_order_earning_credits', to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
        migrations.AddField(
            model_name='masterorderearningcredit',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_earning_credit', to='order.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='masterwithdrawalrequest',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
    ]
