# Generated by Django 5.2.6 on 2025-12-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type_category',
            field=models.CharField(choices=[('by_master', 'По категории мастера'), ('by_car', 'По категории машины'), ('by_order', 'По категории заказа')], max_length=255, verbose_name='Тип категории'),
        ),
    ]
