# Generated by Django 5.2.6 on 2025-12-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_type_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='categories/icons/', verbose_name='Иконка категории'),
        ),
    ]
