# Generated by Django 5.2.6 on 2026-01-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='service_type',
            field=models.CharField(blank=True, default='', help_text='Общий тип услуги для связи между by_order и by_master категориями (например: remont, diagnostika, zamena)', max_length=100, verbose_name='Тип услуги'),
        ),
    ]
