# Generated by Django 5.2.6 on 2026-01-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_category_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='service_type',
            field=models.CharField(blank=True, default='', help_text='Общий тип услуги для связи между by_order и by_master категориями. Примеры: Ремонт, Диагностика, Замена, Техобслуживание, Шиномонтаж, Покраска, Кузовной ремонт, Электрика, Кондиционер, Тюнинг и другие', max_length=100, verbose_name='Тип услуги'),
        ),
    ]
