# Generated by Django 5.2.6 on 2025-10-20 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0007_alter_masterservice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Подробное описание проблемы или услуги', verbose_name='Описание заказа')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус заказа')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('high', 'Высокий')], default='low', max_length=20, verbose_name='Приоритет заказа')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Дополнительная информация о заказе', verbose_name='Дополнительные данные')),
                ('location', models.TextField(help_text='Адрес или описание места', verbose_name='Местоположение')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Широта местоположения', max_digits=10, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Долгота местоположения', max_digits=10, null=True, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('expiration_time', models.DateTimeField(blank=True, help_text='Время истечения заказа (1 день с момента создания)', null=True, verbose_name='Время истечения')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='master.master', verbose_name='Мастер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
