# Generated by Django 5.2.6 on 2025-12-06 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='master_in_master',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders_master_in_master', to=settings.AUTH_USER_MODEL, verbose_name='Мастер в мастере'),
        ),
    ]
