# Generated by Django 5.2.6 on 2025-12-07 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_remove_car_type_car_car_category'),
        ('categories', '0003_alter_category_type_category'),
        ('order', '0003_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='data',
        ),
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ManyToManyField(related_name='orders', to='car.car', verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ManyToManyField(related_name='orders', to='categories.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='order',
            name='master_in_master',
            field=models.ManyToManyField(blank=True, related_name='orders_master_in_master', to=settings.AUTH_USER_MODEL, verbose_name='Мастер в мастере'),
        ),
    ]
