# Generated by Django 5.2.6 on 2026-01-21 17:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_delete_masterinmaster'),
        ('order', '0004_remove_order_data_order_car_order_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('order', 'user', 'master')},
        ),
        migrations.RemoveField(
            model_name='order',
            name='master_in_master',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='master_in_master',
        ),
    ]
