# Generated by Django 5.2.6 on 2026-01-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_masters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Запланированный заказ',
                'verbose_name_plural': 'Запланированные заказы (по дате)',
                'ordering': ['scheduled_date', 'scheduled_time_start'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
        migrations.CreateModel(
            name='SOSOrder',
            fields=[
            ],
            options={
                'verbose_name': 'SOS заказ',
                'verbose_name_plural': 'SOS заказы (экстренная помощь)',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('scheduled', 'Запланированный (по дате)'), ('sos', 'SOS/Экстренный')], default='scheduled', help_text='Scheduled - запланированный заказ по дате, SOS - экстренная помощь', max_length=20, verbose_name='Тип заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Дата визита к мастеру (только для запланированных заказов)', null=True, verbose_name='Запланированная дата'),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_time_end',
            field=models.TimeField(blank=True, help_text='Время окончания визита (например: 11:00)', null=True, verbose_name='Конец визита'),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_time_start',
            field=models.TimeField(blank=True, help_text='Время начала визита (например: 10:00)', null=True, verbose_name='Начало визита'),
        ),
    ]
