# Generated by Django 5.2.6 on 2026-01-31 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_master_name'),
        ('order', '0007_scheduledorder_sosorder_order_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Скидка на заказ (в процентах или сумме)', max_digits=10, verbose_name='Скидка'),
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('master_service_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_services', to='master.masterserviceitems', verbose_name='Услуга мастера')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_services', to='order.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Услуга в заказе',
                'verbose_name_plural': 'Услуги в заказах',
                'ordering': ['-created_at'],
                'unique_together': {('order', 'master_service_item')},
            },
        ),
    ]
