# Generated by Django 5.2.6 on 2026-01-31 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_discount_orderservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Рейтинг от 1 до 5', verbose_name='Рейтинг')),
                ('comment', models.TextField(blank=True, help_text='Текст отзыва', null=True, verbose_name='Комментарий')),
                ('tag', models.CharField(choices=[('fast_work', 'Оперативная работа'), ('no_overpay', 'Без переплат'), ('deadline', 'Соблюдение сроков'), ('always_available', 'Всегда на связи'), ('individual_approach', 'Индивидуальный подход'), ('polite', 'Вежливость')], help_text='Что понравилось в работе мастера', max_length=50, verbose_name='Тег отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order', models.OneToOneField(help_text='Заказ, к которому относится отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='order.order', verbose_name='Заказ')),
                ('reviewer', models.ForeignKey(help_text='Пользователь, который оставил отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Средний рейтинг на основе всех отзывов', max_digits=3, verbose_name='Средний рейтинг')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рейтинг пользователя',
                'verbose_name_plural': 'Рейтинги пользователей',
                'ordering': ['-average_rating'],
            },
        ),
    ]
