# Generated by Django 5.2.6 on 2026-05-03 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_chat_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Принят мастером'),
        ),
        migrations.AddField(
            model_name='order',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Прибытие'),
        ),
        migrations.AddField(
            model_name='order',
            name='completion_pin',
            field=models.CharField(blank=True, default='', help_text='Генерируется при переходе в «в работе»; клиент вводит при complete', max_length=8, verbose_name='PIN завершения для клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='on_the_way_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Выезд (в пути)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принят мастером'), ('on_the_way', 'В пути'), ('arrived', 'Прибыл'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.CreateModel(
            name='MasterOrderCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('customer_no_show', 'Клиент не вышел / не на месте'), ('vehicle_not_ready', 'Авто не готово к работе'), ('emergency', 'Форс-мажор'), ('other', 'Другое')], max_length=32, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_order_cancellations', to=settings.AUTH_USER_MODEL, verbose_name='Мастер (пользователь)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_cancellations', to='order.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Отмена заказа мастером',
                'verbose_name_plural': 'Отмены заказов мастерами',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderWorkCompletionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_work_completion/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_completion_images', to='order.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Фото завершения работы',
                'verbose_name_plural': 'Фото завершения работы',
                'ordering': ['created_at'],
            },
        ),
    ]
