# Generated by Django 5.2.6 on 2025-09-26 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_car', models.CharField(blank=True, choices=[('Легковой', 'Легковой'), ('Мото', 'Мото'), ('Грузовой', 'Грузовой'), ('Автобус', 'Автобус'), ('Техника', 'Техника'), ('Гидро', 'Гидро')], max_length=255, null=True, verbose_name='Тип машины')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название машины')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='Марка машины')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель машины')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска машины')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['-created_at'],
            },
        ),
    ]
