# Generated by Django 5.2.6 on 2025-12-06 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_remove_car_name'),
        ('categories', '0002_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='type_car',
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='categories.category', verbose_name='Категория'),
        ),
    ]
