# Generated by Django 5.1.4 on 2025-09-26 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тип услуги',
                'verbose_name_plural': 'Типы услуг',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('card_number', models.CharField(blank=True, max_length=19, verbose_name='Номер карты')),
                ('card_expiry_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='Месяц истечения')),
                ('card_expiry_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год истечения')),
                ('card_cvv', models.CharField(blank=True, max_length=4, verbose_name='CVV/CVC')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Рейтинг')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Всего заказов')),
                ('completed_orders', models.PositiveIntegerField(default=0, verbose_name='Выполненных заказов')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Опыт работы (лет)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='Рабочие часы')),
                ('reserved_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Зарезервированная сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('services', models.ManyToManyField(blank=True, related_name='masters', to='master.servicetype', verbose_name='Предоставляемые услуги')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
                'ordering': ['-created_at'],
            },
        ),
    ]
