# Generated by Django 5.1.4 on 2025-09-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='services',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.JSONField(default=list, help_text='Список выбранных услуг', verbose_name='Предоставляемые услуги'),
        ),
    ]
