# Generated by Django 5.1.4 on 2025-09-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_remove_master_services_delete_servicetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='address',
        ),
        migrations.RemoveField(
            model_name='master',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='master',
            name='longitude',
        ),
    ]
