# Generated by Django 5.1.4 on 2025-09-26 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_remove_master_address_remove_master_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='completed_orders',
        ),
        migrations.RemoveField(
            model_name='master',
            name='description',
        ),
        migrations.RemoveField(
            model_name='master',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='master',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='master',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='master',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='master',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='master',
            name='total_orders',
        ),
        migrations.RemoveField(
            model_name='master',
            name='working_hours',
        ),
    ]
