# Generated by Django 5.2.6 on 2025-10-17 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_master_address_master_latitude_master_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание услуги')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена')),
                ('price_from', models.BooleanField(default=False, verbose_name='Цена "от" (от указанной суммы)')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('category', models.CharField(choices=[('diagnostics', 'Диагностика электроники'), ('service', 'Сервис и ТО'), ('tire_repair', 'Шиномонтаж'), ('towing', 'Буксировка'), ('car_wash', 'Автомойка'), ('road_help', 'Помощь на дороге')], max_length=50, verbose_name='Категория услуги')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MasterContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('working_hours_start', models.TimeField(default='09:00', verbose_name='Начало рабочего дня')),
                ('working_hours_end', models.TimeField(default='19:00', verbose_name='Конец рабочего дня')),
                ('working_days', models.JSONField(default=list, help_text='Список дней недели (0=Понедельник, 6=Воскресенье)', verbose_name='Рабочие дни')),
                ('is_available_24_7', models.BooleanField(default=False, verbose_name='Доступен 24/7')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='master.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Контактная информация мастера',
                'verbose_name_plural': 'Контактная информация мастеров',
            },
        ),
        migrations.CreateModel(
            name='MasterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Индивидуальная цена')),
                ('custom_price_from', models.BooleanField(default=False, verbose_name='Индивидуальная цена "от"')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_services', to='master.master', verbose_name='Мастер')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга мастера',
                'verbose_name_plural': 'Услуги мастеров',
                'ordering': ['service__category', 'service__name'],
                'unique_together': {('master', 'service')},
            },
        ),
    ]
