# Generated by Django 5.2.6 on 2025-10-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_service_mastercontactinfo_masterservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterservice',
            options={'ordering': ['name'], 'verbose_name': 'Услуга мастера', 'verbose_name_plural': 'Услуги мастеров'},
        ),
        migrations.AlterUniqueTogether(
            name='masterservice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='master',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='master',
            name='working_time',
            field=models.CharField(default='', max_length=100, verbose_name='Рабочее время'),
        ),
        migrations.AddField(
            model_name='masterservice',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='masterservice',
            name='price_from',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена от'),
        ),
        migrations.AddField(
            model_name='masterservice',
            name='price_to',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена до'),
        ),
        migrations.DeleteModel(
            name='MasterContactInfo',
        ),
        migrations.RemoveField(
            model_name='masterservice',
            name='custom_price',
        ),
        migrations.RemoveField(
            model_name='masterservice',
            name='custom_price_from',
        ),
        migrations.RemoveField(
            model_name='masterservice',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='masterservice',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
