# Generated by Django 5.2.6 on 2025-10-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_alter_masterservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='service_type',
            field=models.CharField(choices=[('diagnostics', 'Диагностика электроники'), ('service', 'Сервис и СТО'), ('tire_repair', 'Шиномонтаж'), ('towing', 'Буксировка'), ('car_wash', 'Автомойка'), ('road_help', 'Помощь на дороге')], default='', max_length=100, verbose_name='Тип услуги'),
        ),
    ]
