# Generated by Django 5.2.6 on 2025-10-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_master_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='master',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Долгота'),
        ),
    ]
