# Generated by Django 5.2.6 on 2025-10-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_alter_master_latitude_alter_master_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс мастера'),
        ),
    ]
