# Generated by Django 5.2.6 on 2025-10-21 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_master_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='services',
        ),
    ]
