# Generated by Django 5.2.6 on 2025-10-21 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_remove_master_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
