# Generated by Django 5.2.6 on 2025-10-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_alter_master_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Город'),
        ),
    ]
