# Generated by Django 5.2.6 on 2025-11-08 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_alter_master_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='MasterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='master_images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_images', to='master.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Изображение мастера',
                'verbose_name_plural': 'Изображения мастеров',
                'ordering': ['-created_at'],
            },
        ),
    ]
