# Generated by Django 5.2.6 on 2025-12-06 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_icon'),
        ('master', '0014_master_description_masterimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterservice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Услуга мастера', 'verbose_name_plural': 'Услуги мастеров'},
        ),
        migrations.RemoveField(
            model_name='master',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='masterservice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='masterservice',
            name='price_from',
        ),
        migrations.RemoveField(
            model_name='masterservice',
            name='price_to',
        ),
        migrations.AddField(
            model_name='master',
            name='category',
            field=models.ManyToManyField(related_name='master_categories', to='categories.category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='MasterServiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Название услуги')),
                ('price_from', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена от')),
                ('price_to', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_service_items', to='categories.category', verbose_name='Категория')),
                ('master_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_service_items', to='master.masterservice', verbose_name='Услуга мастера')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterInMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_in_masters', to='master.master', verbose_name='Мастер')),
                ('masterinmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_in_master_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Мастер в мастере')),
            ],
            options={
                'verbose_name': 'Мастер в мастере',
                'verbose_name_plural': 'Мастера в мастерах',
                'ordering': ['-created_at'],
                'unique_together': {('master', 'masterinmaster')},
            },
        ),
    ]
