# Generated by Django 5.2.6 on 2025-12-06 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_icon'),
        ('master', '0015_alter_masterservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterinmaster',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='master_in_master_categories', to='categories.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
