# Generated by Django 5.2.6 on 2026-01-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_masterinmaster_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterInMaster',
        ),
    ]
