# Generated by Django 5.2.6 on 2026-01-21 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_delete_masterinmaster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_employments', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='master.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Сотрудник мастерской',
                'verbose_name_plural': 'Сотрудники мастерских',
                'ordering': ['added_at'],
                'unique_together': {('master', 'employee')},
            },
        ),
    ]
