# Generated by Django 5.2.6 on 2026-01-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_masteremployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Название мастерской (например: "СТО Авто-Сервис")', max_length=255, verbose_name='Название мастерской'),
        ),
    ]
