# Generated by Django 5.2.6 on 2026-04-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_master_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='alfa_binding_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Идентификатор связки Альфа-Банк'),
        ),
        migrations.AddField(
            model_name='master',
            name='card_holder_name',
            field=models.CharField(blank=True, default='', max_length=26, verbose_name='Имя держателя карты (латиница)'),
        ),
    ]
