# Generated by Django 5.2.6 on 2026-04-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_master_alfa_card_binding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='alfa_binding_id',
        ),
        migrations.RemoveField(
            model_name='master',
            name='card_cvv',
        ),
        migrations.RemoveField(
            model_name='master',
            name='card_expiry_month',
        ),
        migrations.RemoveField(
            model_name='master',
            name='card_expiry_year',
        ),
        migrations.RemoveField(
            model_name='master',
            name='card_holder_name',
        ),
        migrations.RemoveField(
            model_name='master',
            name='card_number',
        ),
    ]
