# Generated by Django 5.2.6 on 2026-04-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_remove_master_bank_card_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='master',
            name='reserved_amount',
        ),
    ]
