# Generated by Django 5.2.6 on 2026-01-31 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='initiator',
            field=models.ForeignKey(blank=True, help_text='Пользователь, создавший чат', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_chats', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор'),
        ),
    ]
